dbt_acdc_demo:
  target: dev
  outputs:
    dev:
      type: glue
      query-comment: "This is a glue dbt example"
      role_arn: arn:aws:iam::026090528544:role/AwsGlueSessionUserRestrictedServiceRole-dbtGlueExecutor
      region: ap-southeast-2
      workers: 2
      worker_type: G.1X
      idle_timeout: 10
      schema: "glue-db-acdc-dbt-test-clean"
      session_provisioning_timeout_in_seconds: 120
      location: "s3://acdc-dbt-test-clean/dbt/"
      glue_session_reuse: true
