{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "readAndWriteDatabases",
            "Action": [
                "glue:SearchTables",
                "glue:BatchCreatePartition",
                "glue:CreatePartitionIndex",
                "glue:DeleteDatabase",
                "glue:GetTableVersions",
                "glue:GetPartitions",
                "glue:DeleteTableVersion",
                "glue:UpdateTable",
                "glue:DeleteTable",
                "glue:DeletePartitionIndex",
                "glue:GetTableVersion",
                "glue:UpdateColumnStatisticsForTable",
                "glue:CreatePartition",
                "glue:UpdateDatabase",
                "glue:CreateTable",
                "glue:GetTables",
                "glue:GetDatabases",
                "glue:GetTable",
                "glue:GetDatabase",
                "glue:GetPartition",
                "glue:UpdateColumnStatisticsForPartition",
                "glue:CreateDatabase",
                "glue:BatchDeleteTableVersion",
                "glue:BatchDeleteTable",
                "glue:DeletePartition",
                "glue:GetUserDefinedFunctions",
                "lakeformation:ListResources",
                "lakeformation:BatchGrantPermissions",
                "lakeformation:ListPermissions", 
                "lakeformation:GetDataAccess",
                "lakeformation:GrantPermissions",
                "lakeformation:RevokePermissions",
                "lakeformation:BatchRevokePermissions",
                "lakeformation:AddLFTagsToResource",
                "lakeformation:RemoveLFTagsFromResource",
                "lakeformation:GetResourceLFTags",
                "lakeformation:ListLFTags",
                "lakeformation:GetLFTag"
            ],
            "Resource": [
                "arn:aws:glue:ap-southeast-2:026090528544:catalog",
                "arn:aws:glue:ap-southeast-2:026090528544:table/glue_db_acdc_dbt_test_clean/*",
                "arn:aws:glue:ap-southeast-2:026090528544:database/glue_db_acdc_dbt_test_clean"
            ],
            "Effect": "Allow"
        },
        {
            "Sid": "readOnlyDatabases",
            "Action": [
                "glue:SearchTables",
                "glue:GetTableVersions",
                "glue:GetPartitions",
                "glue:GetTableVersion",
                "glue:GetTables",
                "glue:GetDatabases",
                "glue:GetTable",
                "glue:GetDatabase",
                "glue:GetPartition",
                "lakeformation:ListResources",
                "lakeformation:ListPermissions"
            ],
            "Resource": [
                "arn:aws:glue:ap-southeast-2:026090528544:table/glue_db_acdc_dbt_test_raw/*",
                "arn:aws:glue:ap-southeast-2:026090528544:database/glue_db_acdc_dbt_test_raw",
                "arn:aws:glue:ap-southeast-2:026090528544:database/default",
                "arn:aws:glue:ap-southeast-2:026090528544:database/global_temp"
            ],
            "Effect": "Allow"
        },
        {
            "Sid": "storageAllBuckets",
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::acdc-dbt-test-clean",
                "arn:aws:s3:::acdc-dbt-test-raw"
            ],
            "Effect": "Allow"
        },
        {
            "Sid": "readAndWriteBuckets",
            "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::acdc-dbt-test-clean/*"
            ],
            "Effect": "Allow"
        },
        {
            "Sid": "readOnlyBuckets",
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::acdc-dbt-test-raw/*"
            ],
            "Effect": "Allow"
        }
    ]
}